---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: database
  namespace: "support-system"
  labels:
    app: support-collect-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-collect-database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: support-collect-database
      annotations:
    spec:
      containers:
      - env:
        - name: MYSQL_ROOT_HOST
          value: '%'
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_ROOT_PASSWORD
              name: mysql-secret
              optional: false
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql-secret
              optional: false
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-secret
              optional: false
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: MYSQL_DATABASE
              name: mysql-secret
              optional: false
        image: mysql/mysql-server:5.7
        name: database
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: support-collect
          subPath: data
      volumes:
      - name: support-collect
        persistentVolumeClaim:
          claimName: support-collect

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: support-collect
  namespace: "support-system"
  labels:
    app: support-collect-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: support-collect-server
  template:
    metadata:
      labels:
        app: support-collect-server
      annotations:
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          value: 'support-database'
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              key: MYSQL_USER
              name: mysql-secret
              optional: false
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MYSQL_PASSWORD
              name: mysql-secret
              optional: false
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              key: MYSQL_DATABASE
              name: mysql-secret
              optional: false
        image: cube8021/support-collect:server-BUILD_NUMBER
        name: server
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 2
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 2
          successThreshold: 2
          timeoutSeconds: 2

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: worker
  namespace: "support-system"
  labels:
    app: support-collect-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: support-collect-worker
  template:
    metadata:
      labels:
        app: support-collect-worker
      annotations:
    spec:
      serviceAccountName: support-collect
      containers:
        - name: worker
          image: cube8021/support-collect:worker-BUILD_NUMBER
